done business logic for comments
GBDev1-FirstTeam/new-habr pull request #11
Opened 2023-02-05 12:56 UTC by vanbogota

2023-02-05 13:07 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +    //[Authorize(Roles = "admin")] какие у нас в итоге роли будут?
User, Moderator, Administrator

2023-02-05 13:07 UTC, Narendin commented on 01. Presentation/NewHabr.WebApi/Program.cs
> +        services.ConfigureAutoMapper(typeof(ArticleProfile).Assembly, typeof(CommentProfile).Assembly);
зачем это добавление? ArticleProfile и CommentProfile в одной сборке находятся

2023-02-05 13:08 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +public class CommentController : ControllerBase
Переименовать контроллер в CommentsController

2023-02-05 13:08 UTC, Narendin commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +    {
откуда возьмется флаг trackChanges и зачем он вообще тут нужен?

2023-02-05 13:10 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +    public async Task<ActionResult<CommentDto>> GetByUserIdAsync([FromRoute] Guid id, CancellationToken cancellationToken)
маршрут comments/10 должен вернуть комментарий с id 10
предлагаю этот метод убрать из контроллера коментариев

2023-02-05 13:11 UTC, Narendin commented on 02. Business/NewHabr.Domain/Dto/CreateCommentRequest.cs
> +    public string? Text { get; set; }
если Text - [NotNull], то поучему тип 'string?', которой прям указан как nullable?

2023-02-05 13:11 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +    public async Task<ActionResult<List<CommentDto>>> GetAllAsync(bool trackChanges, CancellationToken cancellationToken)
чтобы получить все комментарии путь должен быть /comments, без лишних добавок

2023-02-05 13:12 UTC, Narendin commented on 02. Business/NewHabr.Domain/Exceptions/EntityNotFoundException.cs
> +    public EntityNotFoundException() : base($"Entity type of {nameof(TEntity)} not found.")
если я правильно помню, nameof(TEntity) выдаст "TEntity" в результате. Правильно писать  typeof(TEntity).Name

2023-02-05 13:13 UTC, Narendin commented on 03. DAL/NewHabr.DAL/Repository/ReporitoryBase.cs
> +    public async Task<ICollection<TEntity>> GetAllAsync(bool trackChanges = false, CancellationToken cancellationToken = default)
а следующий метод не требуется удалить? Там же то же самое, только без возможности указания флага trackChanges

2023-02-05 13:17 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +    public async Task<ActionResult<List<CommentDto>>> GetByUserIdAsync([FromRoute] Guid userId, bool trackChanges, CancellationToken cancellationToken)
еще один метод только с другим маршрутом?
путь /comments/user/10 - не очевидно что должно прийти в ответ, если комментарии пользователя то путь должен быть /users/<userId>/comments

2023-02-05 13:19 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +    public async Task<ActionResult<List<CommentDto>>> GetByArticleIdAsync([FromRoute] Guid articleId, bool trackChanges, CancellationToken cancellationToken)
путь для получения коментов конкретной статьи должен быть /articles/<articleID>/comments

2023-02-05 13:22 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Program.cs
> +        services.ConfigureAutoMapper(typeof(ArticleProfile).Assembly, typeof(CommentProfile).Assembly);
если сборка такая же как и остальные, то это строка лишняя

2023-02-05 13:23 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/CommentService.cs
> +        await _repositoryManager.SaveAsync(cancellationToken);
нет проверки на существование коммента, который просят удалить

2023-02-05 13:30 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/CommentService.cs
> +        _repositoryManager.CommentRepository.Create(newComment);
сервис должен проставлять дату создания комментария, верить входящим из вне данным нельзя

2023-02-05 13:32 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/CommentService.cs
> +        await _repositoryManager.SaveAsync(cancellationToken);
заметил что в модели коментов не хватает поля ModifiedAt, если мы даем изменять коменты, надо и дату проставлять, либо убрать модификацию коментов

2023-02-05 13:34 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Exceptions/CommentNotFoundException.cs
> +public class CommentNotFoundException : EntityNotFoundException<Comment, Guid>
Класс исключения создали, а где его бросаем я не увидел

2023-02-05 13:34 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Exceptions/EntityNotFoundException.cs
> +public abstract class EntityNotFoundException<TEntity, TId> : Exception
Класс исключения создали, а где его бросаем я не увидел

2023-02-05 13:35 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/CommentService.cs
> +        var updateComment = _mapper.Map<Comment>(data);
нет проверки на существование коммента, который просят обновить

2023-02-06 06:11 UTC, Narendin commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentController.cs
> +    {
логгер надо получать как ILogger<CommentsController> logger

2023-02-08 04:07 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentsController.cs
> +    public async Task<ActionResult<List<CommentDto>>> GetAllAsync(CancellationToken cancellationToken)
Имена методов в контроллерах должны быть без суффикса Async 
https://github.com/dotnet/aspnetcore/issues/4849

2023-02-08 04:08 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentsController.cs
> +    [HttpGet("user/{userId}/comments")]
в таком случае маршрут будет /comments/user/{userId}/comments - это не правильно
предлагаю убрать этот метод целиком, и сделаем его в контроллене users

2023-02-08 04:10 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentsController.cs
> +    [HttpGet("article/{articleId}/comments")]
неправильный путь - убрать метод, сделаем в контроллере articles

2023-02-08 04:10 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentsController.cs
> +    public async Task<ActionResult> UpdateAsync([FromBody] CommentDto commentDto, CancellationToken cancellationToken)
Имена методов в контроллерах должны быть без суффикса Async 
https://github.com/dotnet/aspnetcore/issues/4849

2023-02-08 04:12 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentsController.cs
>      [HttpPut]
путь для модификации комента должен быть с ид
/comments/{id}

2023-02-08 04:12 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentsController.cs
> +    public async Task<ActionResult> DeleteAsync([FromRoute] Guid id, CancellationToken cancellationToken)
Имена методов в контроллерах должны быть без суффикса Async 
https://github.com/dotnet/aspnetcore/issues/4849

2023-02-08 04:19 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/CommentService.cs
> +        var comments = await _repositoryManager.CommentRepository.GetByArticleIdAsync(articleId, cancellationToken: cancellationToken);
поиск статьи через репозиторий комментариев?

2023-02-08 04:50 UTC, EvgeniyRuban requested changes

2023-02-08 04:50 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Domain/Dto/CreateCommentRequest.cs
> +    public long CreatedAt { get; set; }
Свойство CreateAt ненужно при запросе

2023-02-08 04:50 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Business/AutoMapperProfiles/CommentProfile.cs
> +        CreateMap<Comment, CommentDto>();
тебе надо явно указать как преобразовывать CreateAt типа DateTimeOffset из Comment в long для CommentDto.
аналогично для ModifiedAt.

В профайле статей есть пример.

2023-02-08 04:57 UTC, EvgeniyRuban commented
Лучше хотя бы прозванивать свои контроллеры через Swagger перед внесением изменений, на предмет простой отработки логики, а то я хотел потестить, а банально на простой операции получения комментариев, получил status code 500 lol.
Про unit тесты я молчу, сам в процессе создания.

2023-02-09 04:33 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CommentsController.cs
> +    public async Task<ActionResult> Createc([FromBody] CreateCommentRequest newComment, CancellationToken cancellationToken)
очепятка в названии метода

2023-02-09 04:53 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Dto/CreateCommentRequest.cs
> +    [NotNull]
этот аттрибут из неймспейса System.Diagnostics.CodeAnalysis по сути не влияет на рантайм, это просто инструкция для статических анализаторов. Так что его надо убрать и поставить Required
текст комментария не может же быть пустой строкой

2023-02-09 04:53 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Dto/UpdateCommentRequest.cs
> +    [NotNull]
тоже самое про notnull

2023-02-09 04:56 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Contracts/Services/ICommentService.cs
> +    /// <exception cref="CommentNotFoundException"></exception>
на мой взгляд, описывать в контракте какие исключения может выбрасывать реализация - такое себе.
ведь контракт не обязывает их сбрасывать.. и вполне могут быть реализации которые не бросают ексепшены )

2023-02-09 04:59 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/CommentService.cs
> +        comment.Id = id;
в классе UpdateCommentRequest нет поля Id, соответственно оно не изменит Id в ентити, зачем эта строка?

2023-02-09 05:04 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/AutoMapperProfiles/CommentProfile.cs
> +            .ForMember(dest => dest.ModifiedAt, e => e.MapFrom(src => new DateTimeOffset(new DateTime(src.ModifiedAt))));
1) попробуй эту конвертацию даты  - она не работает
2) так описывать мапинг полей не обязательно, тут же имена совпадают и маппер поймет самостоятельно. А для того чтобы происходила конвертация datetimeoffset в long надо просто сделать правило для мапинга datetimeoffset в long  _отдельно_
посмотри как я сделал в ветке feature/manage_users

2023-02-10 20:26 UTC, merged