feat: add secure question controller, service, repo
GBDev1-FirstTeam/new-habr pull request #15
Opened 2023-02-07 16:45 UTC by SimeonIksanov

2023-02-08 04:49 UTC, EvgeniyRuban requested changes

2023-02-08 04:49 UTC, EvgeniyRuban commented on 01. Presentation/NewHabr.WebApi/Controllers/SecureQuestionsController.cs
> +[Authorize(Roles = "Administrator")]
В домейн есть файлик с константами, думаю можно брать от туда
Constants.Roles.Administrator

2023-02-08 04:49 UTC, EvgeniyRuban commented on 01. Presentation/NewHabr.WebApi/Controllers/SecureQuestionsController.cs
> +    public async Task<IActionResult> CreateQuestion(SecureQuestionCreateRequest request, CancellationToken cancellationToken)
в названии метода create ты добавляешь суффиксно имя сущности, а в update и delete нет

2023-02-08 04:49 UTC, EvgeniyRuban commented on 01. Presentation/NewHabr.WebApi/Controllers/SecureQuestionsController.cs
> +            return BadRequest();
Из-за того что question в запросе помечен как обязательный, запрос не будет принят и вернется badrequest.
Проверка на null не нужна

2023-02-08 04:49 UTC, EvgeniyRuban commented on 01. Presentation/NewHabr.WebApi/Controllers/SecureQuestionsController.cs
> +
Проверка не нужна

2023-02-08 04:49 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Business/Services/SecureQuestionsService.cs
> +        _repositoryManager.SecureQuestionsRepository.Create(newQuestion);
Можно ли добавлять вопросы которые уже существуют?

2023-02-08 04:49 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Business/Services/SecureQuestionsService.cs
> +    public async Task<ICollection<SecureQuestionDto>> GetAllAsync(bool trackChanges, CancellationToken cancellationToken)
Нужно ли выносить логику трекинга за пределы сервисов?
Должен ли контроллер этим руководить?

2023-02-08 04:49 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Business/Services/SecureQuestionsService.cs
> +        await _repositoryManager.SaveAsync();
токен забыл

2023-02-08 04:49 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Business/Services/SecureQuestionsService.cs
> +        await _repositoryManager.SaveAsync();
токен забыл

2023-02-08 18:20 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/SecureQuestionsController.cs
> +[Authorize(Roles = "Administrator")]
потом отрефачим, когда дойдем до выдачи полномочий

2023-02-09 03:00 UTC, EvgeniyRuban approved these changes

2023-02-10 16:46 UTC, merged