Article service/repository refactoring + unit-tests.
GBDev1-FirstTeam/new-habr pull request #17
Opened 2023-02-09 13:20 UTC by EvgeniyRuban

2023-02-09 14:10 UTC, SimeonIksanov requested changes

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +            .FirstOrDefaultAsync(cancellationToken);
так нельзя делать, у тебя репозиторий "протек" в сервис
вообще FindByCondition и прочие которые возвращают IQueriable должны быть с модификатором доступа protected, а не public как у нас сейчас

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +            .FirstOrDefaultAsync(cancellationToken);
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +
нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +            .FirstOrDefaultAsync(cancellationToken);
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Dto/UpdateArticleRequest.cs
>      [NotNull]
этот notnull вообще ничего не проверяет

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +            .FirstOrDefaultAsync(cancellationToken);
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +            .FirstOrDefaultAsync(cancellationToken);
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +            .FirstOrDefaultAsync(cancellationToken);
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +    private async Task UpdateCategoresAsync(Article article, CreateCategoryRequest[] categoriesDto)
зачем эти массивы, когда есть интерфейсы?

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +                .FirstOrDefaultAsync(c => c.Name == categoryDto.Name);
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +                .FirstOrDefaultAsync(c => c.Name == tagDto.Name);
так нельзя

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Contracts/Repositories/IArticleRepository.cs
> -        CancellationToken cancellationToken = default);
??

2023-02-09 14:10 UTC, SimeonIksanov commented on 02. Business/NewHabr.Domain/Dto/UpdateArticleRequest.cs
> +    public CreateCategoryRequest[] Categories { get; set; } = Array.Empty<CreateCategoryRequest>();
с этими массивами, считаю, зря придумал, надо через интерфейсы

2023-02-09 14:10 UTC, SimeonIksanov commented on 03. DAL/NewHabr.DAL/Repository/ReporitoryBase.cs
> +        return Set.Add(data).Entity.Id;
что это?зачем

2023-02-09 14:57 UTC, EvgeniyRuban commented on 03. DAL/NewHabr.DAL/Repository/ReporitoryBase.cs
> +        return Set.Add(data).Entity.Id;
Мне в тестах нужно было нужно, чтобы при создании сущности, я знал какой у неё id. Допустим есть несколько статей, ты добавляешь очередную и пытаешся проверить её состаяние, а как ты поймешь какая из них та которую ты только, что добавил? Да и в целом мне кажется логично, что при передачи данных для создания сущности, ты получаешь в ответ её id по которому ты дальше можешь ей управлять, если с созданной сущностью продолжается работа.

2023-02-09 15:29 UTC, SimeonIksanov commented on 03. DAL/NewHabr.DAL/Repository/ReporitoryBase.cs
> +        return Set.Add(data).Entity.Id;
при сохранении в бд, в сущности и так проставляется ключевое поле, так что это лишнее

2023-02-11 10:56 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/ArticlesController.cs
> +            return Ok(await _articleService.CreateAsync(request, cancellationToken));
по REST-у в ответ на метод POST полагается послать код 201 и можно вложить новый созданный объект и путь, где этот новый объект можно найти

2023-02-11 11:26 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +        var user = await _repositoryManager.UserRepository.GetByIdAsync(request.UserId);
если гуид автора брать из дто, то автора можно подделывать,
правильно гуид брать из аутентификации

2023-02-11 11:26 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/ArticlesController.cs
>          catch (EntityNotFoundException ex)
в этом блоке try catch не ловится исключение ArticleIsNotApproveException
и кстати лучше написать ArticleNotApprovedException

2023-02-11 11:26 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/CategoriesController.cs
> +            return Ok(await _categoryService.CreateAsync(request, cancellationToken));
на POST надо отвечать 201

2023-02-11 11:26 UTC, SimeonIksanov commented on 01. Presentation/NewHabr.WebApi/Controllers/TagsController.cs
> +            return Ok(await _tagService.CreateAsync(request, cancellationToken));
на POST надо отвечать 201

2023-02-11 11:26 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +
я бы сортировку делал в БД

2023-02-11 11:26 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +        return article.Id;
по ресту возвращать надо объект целиком

2023-02-11 11:26 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/ArticleService.cs
> +            var existsTag = existsTags.FirstOrDefault(c => c.Name == tagDto.Name && !c.Deleted);
existsTag тут вроде и так уже НЕудаленные теги, этот кусок '&& !c.Deleted' кажется дублирующим

2023-02-11 11:26 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/CategoryService.cs
> +        return newCategory.Id;
по ресту полагается возвращать объект целиком

2023-02-11 15:08 UTC, EvgeniyRuban commented on 01. Presentation/NewHabr.WebApi/Controllers/ArticlesController.cs
>          catch (EntityNotFoundException ex)
не ловится, потому, что при этой операции оно не генерируется.

2023-02-11 17:27 UTC, Narendin commented on 02. Business/NewHabr.Domain/Contracts/Repositories/IUserRepository.cs
>      Task<int> GetUsersCountWithSecureQuestionId(int id, CancellationToken cancellationToken);
а в этом методе `= default `на надо?

2023-02-11 17:30 UTC, Narendin commented on 02. Business/NewHabr.Domain/Dto/ArticleDto.cs
> +            && Content == article.Content
может, стринговые поля сравнивать не просто как ==, а делать вот так?
`string.Equal(a, b, StringComparison.OrdinalIgnoreCase) `
Чтобы различия в регистре игнорировать?

2023-02-11 17:35 UTC, Narendin commented on 03. DAL/NewHabr.DAL/Repository/ArticleRepository.cs
> +        await articlesQuery.ForEachAsync(a => a.Comments.OrderByDescending(a => a.CreatedAt), cancellationToken);
Насколько я понимаю, метод OrderByDescending не редактирует коллекцию, а вотзвращает новую, отсортированную. В итоге комментарии так и останутся несортированными.
Если данный функционал оттестирован и комментарии действительно отсортированы в итоге, просьба сообщить об этом.

2023-02-16 08:56 UTC, SimeonIksanov commented
Кстати сказать, тесты в этом ПР тестируют связку Сервис-Репозиторий-Базаданных.
Это не похоже на Unit тестирование. Это скорее интеграционное тестирование.

2023-02-17 16:52 UTC, closed without merging