Fix delete operation.
GBDev1-FirstTeam/new-habr pull request #25
Opened 2023-02-18 22:46 UTC by EvgeniyRuban

- clear default value for cancellation tokens and track changies.

2023-02-19 09:09 UTC, SimeonIksanov requested changes

2023-02-19 09:09 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/TagService.cs
> +        tag.Articles = null;
поясни плиз, для чего эти удаления? у нас же "софт" удаления, зачем рвать связи? они же не мешают

2023-02-19 09:56 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Business/Services/TagService.cs
> +        tag.Articles = null;
Ну, это упростит include для статей, не надо будет делать выборку. Просто сделал include на теги и он слинкованные тебе возвращает. И я подумал ещё, что наверное при создании тегов/категорий можно проверять, есть ли среди удаленных теги с таким же названием, если есть то восстанавливать.

2023-02-19 10:17 UTC, SimeonIksanov commented on 02. Business/NewHabr.Business/Services/TagService.cs
> +        tag.Articles = null;
это не так надо делать.

2023-02-20 09:47 UTC, EvgeniyRuban commented on 02. Business/NewHabr.Business/Services/TagService.cs
> +        tag.Articles = null;
а как?

2023-02-21 15:15 UTC, closed without merging